defaults:
  - _self_
  - datamodule: h5


seed: 12345
# used_gpus=null to not modify CUDA_DEVICE_ORDER and CUDA_VISIBLE_DEVICES. used_gpus=[] such that there are not visible
# gpus, and otherwise, e.g., used_gpus=[0, 2] such that only cuda:0 and cuda:2 are visible to the application.
used_gpus: null
checkpoint: null
run_name: ???
checkpoint_path: "checkpoints/${run_name}"

trainer:
  _target_: pytorch_lightning.Trainer
  accelerator: gpu
  devices: 1
  max_epochs: -1
  deterministic: True
  precision: 16
  limit_val_batches: 1.0
  val_check_interval: 1.0
  check_val_every_n_epoch: 1
  default_root_dir: null
  enable_checkpointing: True
  strategy:
    _target_: pytorch_lightning.strategies.ddp.DDPStrategy
    find_unused_parameters: False
